version:  '3.2'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=1StrongPwd!!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  api:
    image: aspnetcore/demoapp
    ports: 
      - "8080:80"
    depends_on: 
      - ms-sql-server